name: build-docker

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-docker.yml"
      - "scripts/patch-npm-nginx.sh"
      - "Dockerfile"
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Checkout build files
        uses: actions/checkout@v4
        with:
          repository: NginxProxyManager/docker-nginx-full
          ref: master
          path: build
      - name: Patch build files
        run: |
          cp -rf build/* ./
          cd scripts
          ./patch-npm.sh
          echo "DATE_TAG=$(date -I)" >> "$GITHUB_ENV"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            darkclip/nginx:latest
            darkclip/nginx:${{ env.DATE_TAG }}
