name: build-nginx

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-nginx.yml"
      - "Dockerfile"
  workflow_dispatch:

jobs:
  build-nginx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Get date for tag
        run: |
          echo "DATE_TAG=$(date -I)" >> "$GITHUB_ENV"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            darkclip/nginx:latest
            darkclip/nginx:${{ env.DATE_TAG }}
