name: build-builder

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-builder.yml"
      - "scripts/**"
      - "rootfs/**"
      - "Dockerfile.builder"
  workflow_dispatch:

jobs:
  build-builder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.builder
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            darkclip/nginx-builder:latest
